"use client";

import React, { useState, useEffect } from "react";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "http://localhost:5000";

export default function SalesReports() {
  const [reports, setReports] = useState([]);
  const [filterType, setFilterType] = useState("all");
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");
  const [page, setPage] = useState(1);
  const [total, setTotal] = useState(0);
  const [limit] = useState(20);

  const [preview, setPreview] = useState(null); // report doc for modal

  async function load() {
    try {
      setLoading(true);
      setErr("");

      const params = new URLSearchParams({
        page: String(page),
        limit: String(limit),
      });
      if (search.trim()) params.set("q", search.trim());
      if (filterType !== "all") params.set("type", filterType);

      const res = await fetch(`${API_BASE}/api/sales/reports?${params.toString()}`, {
        credentials: "include",
        headers: { Accept: "application/json" },
      });
      if (!res.ok) throw new Error(await res.text());
      const json = await res.json();
      setReports(json.items || []);
      setTotal(json.total || 0);
    } catch (e) {
      console.error("load reports failed:", e);
      setErr("Failed to load reports");
      setReports([]);
      setTotal(0);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); /* eslint-disable-next-line */ }, [filterType, page]);
  // Trigger search explicitly (e.g., debounce or enter)
  const onSearch = (e) => { e.preventDefault(); setPage(1); load(); };

  const openPreview = async (id) => {
    try {
      const res = await fetch(`${API_BASE}/api/sales/reports/${id}`, { credentials: "include" });
      if (!res.ok) throw new Error(await res.text());
      const doc = await res.json();
      setPreview(doc);
    } catch (e) {
      alert("Failed to load report preview");
    }
  };

  const closePreview = () => setPreview(null);

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-800">Sales Reports</h1>
        <p className="text-gray-500 mt-1">
          View reports generated by managers to understand product performance.
        </p>
      </div>

      {/* Filters */}
      <form onSubmit={onSearch} className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 gap-4">
        <input
          type="text"
          placeholder="Search reports..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="px-4 py-2 border rounded-md w-full sm:w-1/3 focus:outline-none focus:ring-2 focus:ring-green-500"
        />

        <div className="flex gap-3">
          <select
            value={filterType}
            onChange={(e) => { setPage(1); setFilterType(e.target.value); }}
            className="px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-green-500"
          >
            <option value="all">All Types</option>
            <option value="PDF">PDF</option>
            <option value="Excel">Excel</option>
            <option value="CSV">CSV</option>
          </select>

          <button
            type="submit"
            className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
          >
            Search
          </button>
        </div>
      </form>

      {/* List */}
      <div className="bg-white rounded-lg shadow divide-y divide-gray-200">
        {loading ? (
          <p className="p-6 text-gray-500 text-center">Loading…</p>
        ) : err ? (
          <p className="p-6 text-red-600 text-center">{err}</p>
        ) : reports.length === 0 ? (
          <p className="p-6 text-gray-500 text-center">No reports found.</p>
        ) : (
          reports.map((r) => (
            <div key={r._id} className="p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h3 className="text-lg font-semibold text-gray-800">{r.name}</h3>
                <p className="text-sm text-gray-500">{r.description}</p>
                <p className="text-xs text-gray-400 mt-1">
                  Period: {new Date(r.from).toLocaleDateString()} - {new Date(r.to).toLocaleDateString()}
                </p>
                <p className="text-xs text-gray-400">Type: {r.type}</p>
                <p className="text-xs text-gray-400">Status: {r.status}</p>
              </div>

              <div className="flex space-x-3">
                <button
                  onClick={() => openPreview(r._id)}
                  className="px-4 py-2 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
                >
                  View
                </button>
                <a
                  href={r.downloadUrl}
                  download
                  className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition"
                >
                  Download
                </a>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Pager */}
      <div className="px-4 py-3 border-t border-gray-200 flex items-center justify-end gap-2 mt-2 bg-white rounded-lg shadow">
        <button
          className="px-3 py-1 border rounded disabled:opacity-50"
          onClick={() => setPage((p) => Math.max(1, p - 1))}
          disabled={page <= 1 || loading}
        >
          Prev
        </button>
        <button
          className="px-3 py-1 border rounded disabled:opacity-50"
          onClick={() => setPage((p) => p + 1)}
          disabled={reports.length < limit || loading}
        >
          Next
        </button>
      </div>

      {/* Preview modal */}
      {preview && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-lg w-full max-w-2xl p-6">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="text-xl font-semibold text-gray-800">{preview.name}</h3>
                <p className="text-sm text-gray-500">{preview.description}</p>
                <p className="text-xs text-gray-400 mt-1">
                  Period: {new Date(preview.from).toLocaleDateString()} - {new Date(preview.to).toLocaleDateString()}
                </p>
              </div>
              <button onClick={closePreview} className="text-gray-500 hover:text-gray-700 text-2xl leading-none">×</button>
            </div>

            <div className="mt-4 grid grid-cols-3 gap-4">
              <div className="bg-gray-50 rounded p-4">
                <div className="text-xs text-gray-500">Total Sales</div>
                <div className="text-lg font-semibold">
                  ${Number(preview.preview?.totalSales || 0).toLocaleString()}
                </div>
              </div>
              <div className="bg-gray-50 rounded p-4">
                <div className="text-xs text-gray-500">Orders</div>
                <div className="text-lg font-semibold">
                  {Number(preview.preview?.ordersCount || 0).toLocaleString()}
                </div>
              </div>
              <div className="bg-gray-50 rounded p-4">
                <div className="text-xs text-gray-500">Top Items</div>
                <div className="text-lg font-semibold">
                  {(preview.preview?.topProducts?.length || 0).toLocaleString()}
                </div>
              </div>
            </div>

            <div className="mt-6">
              <h4 className="font-medium text-gray-800 mb-2">Top Products</h4>
              <div className="border rounded">
                <table className="min-w-full text-sm">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="text-left px-3 py-2">Product</th>
                      <th className="text-right px-3 py-2">Qty</th>
                      <th className="text-right px-3 py-2">Revenue</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(preview.preview?.topProducts || []).map((p, idx) => (
                      <tr key={idx} className="border-t">
                        <td className="px-3 py-2">{p.name || p.productId}</td>
                        <td className="px-3 py-2 text-right">{p.qty}</td>
                        <td className="px-3 py-2 text-right">${Number(p.revenue || 0).toLocaleString()}</td>
                      </tr>
                    ))}
                    {(!preview.preview?.topProducts || preview.preview.topProducts.length === 0) && (
                      <tr><td className="px-3 py-4 text-center text-gray-500" colSpan={3}>No product breakdown</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-3">
              <a
                href={preview.downloadUrl}
                download
                className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
              >
                Download
              </a>
              <button onClick={closePreview} className="px-4 py-2 border rounded-md">Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
